spring.application.name=main
jwt.secret=4Ch4v3D3Cr1pt0gr4f14S3r4B4nk414002892230S0mD0J4p0n3sQu3V41DPl4st4t1on3
jwt.expiration-millis=3600000

spring.datasource.url=jdbc:h2:file:./data/chatdb;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.h2.console.enabled=true
spring.sql.init.mode=always
spring.jpa.hibernate.ddl-auto=update


# Porta do servidor
#server.port=8080
#
## Habilita SSL
#server.ssl.enabled=true
#
## Local do keystore
#server.ssl.key-store=classpath:keystore.p12
#server.ssl.key-store-password=minhaSenha123
#server.ssl.key-store-type=PKCS12
#server.ssl.key-alias=meu-alias
#
